### ISSUE TITLE
Feature: Grid.from_array filter to accept other criteria

### ISSUE THREAD

**Issue by mwtoews** [mwtoews/gridit#17]
The request is to allow `filter` to accept more than one value from an iterable. This would allow a Grid definition to be created without needing to merge several features beforehand.

**Comment by wkitlasten** [comment]
It seems filter only picks up the first feature with attribute. I noticed this when I was trying to resample an existing grid. Reproduced via:
```
Grid.write_vector(mg, idomain, fname, attribute='idom')
nmg = Grid.from_vector(fname, filter={'idom': 1}, resolution=500)

nmg
<Grid: resolution=500.0, shape=(1, 1), top_left=(1688000.0, 5417500.0) />
```
