### ISSUE TITLE
Option to build Grid from flopy modelgrid object 

### ISSUE THREAD

**Issue by briochh** [mwtoews/gridit#19]
I think that most of the flopy Modflow6 object is superfluous for gridit (at least for the `Grid.from_modflow()` method).
Indeed the lines:

> if hasattr(model, "bas6"):
>     domain = model.bas6.ibound.array
> else:
>     domain = model.dis.idomain.array

could be simplified to simply
`domain = model.modelgrid.idomain`

Perhaps a mini refactor could support setting up with just the `modelgrid` component of the `flopy.Modflow` object?

**Comment by mwtoews** [comment]
Closed by #20
